name: CI ex_password

on: 
  push: 
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          pip install pytest
          pytest
      - name: build docker image
        run:
          docker build -t ajc_test_password .
      - name: run docker image 
        run: 
          docker run ajc_test_password
      - name: docker login
        env:
          dock_username: ${{secrets.DOCKER_USERNAME}}
          dock_password: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $dock_username -p $dock_password
      - name: docker tag
        run: docker tag ajc_test_password:latest kevindalmasso99/ajc-devops:test_password
      - name: docker push
        run: docker push kevindalmasso99/ajc-devops:test_password